# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setFixedSize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(390, 10, 401, 581))
        self.textBrowser.setObjectName("textBrowser")
        self.LineDynamic = QtWidgets.QLineEdit(self.centralwidget)
        self.LineDynamic.setGeometry(QtCore.QRect(10, 20, 351, 21))
        self.LineDynamic.setInputMask("")
        self.LineDynamic.setText("")
        self.LineDynamic.setObjectName("LineDynamic")
        self.HintUserSource = QtWidgets.QLabel(self.centralwidget)
        self.HintUserSource.setGeometry(QtCore.QRect(20, 50, 111, 21))
        self.HintUserSource.setObjectName("HintUserSource")
        self.CheckBoxRepost = QtWidgets.QCheckBox(self.centralwidget)
        self.CheckBoxRepost.setGeometry(QtCore.QRect(20, 78, 91, 21))
        self.CheckBoxRepost.setObjectName("CheckBoxRepost")
        self.CheckBoxReply = QtWidgets.QCheckBox(self.centralwidget)
        self.CheckBoxReply.setGeometry(QtCore.QRect(130, 78, 91, 21))
        self.CheckBoxReply.setObjectName("CheckBoxReply")
        self.CheckBoxLike = QtWidgets.QCheckBox(self.centralwidget)
        self.CheckBoxLike.setGeometry(QtCore.QRect(240, 78, 91, 21))
        self.CheckBoxLike.setObjectName("CheckBoxLike")
        self.HintCondition = QtWidgets.QLabel(self.centralwidget)
        self.HintCondition.setGeometry(QtCore.QRect(20, 150, 101, 21))
        self.HintCondition.setObjectName("HintCondition")
        self.ListUser = QtWidgets.QListView(self.centralwidget)
        self.ListUser.setGeometry(QtCore.QRect(10, 310, 351, 111))
        self.ListUser.setObjectName("ListUser")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(360, 10, 31, 581))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.HintMaxperson = QtWidgets.QLabel(self.centralwidget)
        self.HintMaxperson.setGeometry(QtCore.QRect(20, 180, 131, 21))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(9)
        self.HintMaxperson.setFont(font)
        self.HintMaxperson.setObjectName("HintMaxperson")
        self.HintMinLevel = QtWidgets.QLabel(self.centralwidget)
        self.HintMinLevel.setGeometry(QtCore.QRect(200, 180, 131, 21))
        self.HintMinLevel.setObjectName("HintMinLevel")
        self.SpinTotalGift = QtWidgets.QSpinBox(self.centralwidget)
        self.SpinTotalGift.setGeometry(QtCore.QRect(130, 180, 46, 22))
        self.SpinTotalGift.setObjectName("SpinTotalGift")
        self.SpinMinLevel = QtWidgets.QSpinBox(self.centralwidget)
        self.SpinMinLevel.setGeometry(QtCore.QRect(310, 180, 46, 22))
        self.SpinMinLevel.setObjectName("SpinMinLevel")
        self.HintMinFans = QtWidgets.QLabel(self.centralwidget)
        self.HintMinFans.setGeometry(QtCore.QRect(20, 220, 131, 21))
        self.HintMinFans.setObjectName("HintMinFans")
        self.SpinMinFans = QtWidgets.QSpinBox(self.centralwidget)
        self.SpinMinFans.setGeometry(QtCore.QRect(95, 220, 81, 22))
        self.SpinMinFans.setObjectName("SpinMinFans")
        self.HintMaxFans = QtWidgets.QLabel(self.centralwidget)
        self.HintMaxFans.setGeometry(QtCore.QRect(200, 220, 131, 21))
        self.HintMaxFans.setObjectName("HintMaxFans")
        self.SpinMaxFans = QtWidgets.QSpinBox(self.centralwidget)
        self.SpinMaxFans.setGeometry(QtCore.QRect(280, 220, 81, 22))
        self.SpinMaxFans.setObjectName("SpinMaxFans")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 110, 351, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.HintPersonCount = QtWidgets.QLabel(self.centralwidget)
        self.HintPersonCount.setGeometry(QtCore.QRect(70, 270, 141, 31))
        self.HintPersonCount.setObjectName("HintPersonCount")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 250, 351, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(203, 270, 151, 31))
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setDigitCount(10)
        self.lcdNumber.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        # self.lcdNumber.setProperty("value", 1000.0)
        self.lcdNumber.setProperty("intValue", -1)
        self.lcdNumber.setObjectName("lcdNumber")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 430, 351, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.PushLottery = QtWidgets.QPushButton(self.centralwidget)
        self.PushLottery.setGeometry(QtCore.QRect(22, 547, 331, 41))
        self.PushLottery.setObjectName("PushLottery")
        self.PushClear = QtWidgets.QPushButton(self.centralwidget)
        self.PushClear.setGeometry(QtCore.QRect(20, 490, 331, 41))
        self.PushClear.setObjectName("PushClear")
        self.CheckAutoClear = QtWidgets.QCheckBox(self.centralwidget)
        self.CheckAutoClear.setGeometry(QtCore.QRect(260, 450, 91, 31))
        self.CheckAutoClear.setObjectName("CheckAutoClear")
        self.CheckAutoSave = QtWidgets.QCheckBox(self.centralwidget)
        self.CheckAutoSave.setGeometry(QtCore.QRect(150, 450, 91, 31))
        self.CheckAutoSave.setObjectName("CheckAutoSave")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(130, 50, 231, 21))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.RadioOr = QtWidgets.QRadioButton(self.groupBox)
        self.RadioOr.setGeometry(QtCore.QRect(120, 0, 115, 21))
        self.RadioOr.setObjectName("RadioOr")
        self.RadioAnd = QtWidgets.QRadioButton(self.groupBox)
        self.RadioAnd.setGeometry(QtCore.QRect(0, 0, 115, 21))
        self.RadioAnd.setChecked(True)
        self.RadioAnd.setObjectName("RadioAnd")
        self.CheckBlackList = QtWidgets.QCheckBox(self.centralwidget)
        self.CheckBlackList.setGeometry(QtCore.QRect(20, 450, 101, 31))
        self.CheckBlackList.setObjectName("CheckBlackList")
        self.SpinMaxFans.raise_()
        self.HintMaxFans.raise_()
        self.HintMaxperson.raise_()
        self.HintMinLevel.raise_()
        self.ListUser.raise_()
        self.SpinMinFans.raise_()
        self.progressBar.raise_()
        self.lcdNumber.raise_()
        self.PushLottery.raise_()
        self.CheckBoxReply.raise_()
        self.CheckAutoClear.raise_()
        self.line_3.raise_()
        self.SpinMinLevel.raise_()
        self.LineDynamic.raise_()
        self.line.raise_()
        self.HintPersonCount.raise_()
        self.CheckAutoSave.raise_()
        self.PushClear.raise_()
        self.CheckBoxLike.raise_()
        self.textBrowser.raise_()
        self.line_2.raise_()
        self.HintMinFans.raise_()
        self.HintCondition.raise_()
        self.CheckBoxRepost.raise_()
        self.HintUserSource.raise_()
        self.SpinTotalGift.raise_()
        self.groupBox.raise_()
        self.CheckBlackList.raise_()

        self.retranslateUi(MainWindow)
        self.PushLottery.clicked.connect(MainWindow.Lottery)
        self.PushClear.clicked.connect(MainWindow.CleanLogWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "B站动态抽奖工具"))
        self.LineDynamic.setPlaceholderText(_translate("MainWindow", "请在此输入动态链接或动态ID"))
        self.HintUserSource.setText(_translate("MainWindow", "选择用户来源"))
        self.CheckBoxRepost.setText(_translate("MainWindow", "转发"))
        self.CheckBoxReply.setText(_translate("MainWindow", "评论"))
        self.CheckBoxLike.setText(_translate("MainWindow", "点赞"))
        self.HintCondition.setText(_translate("MainWindow", "筛选用户条件"))
        self.HintMaxperson.setText(_translate("MainWindow", "中奖人数"))
        self.HintMinLevel.setText(_translate("MainWindow", "最低等级"))
        self.HintMinFans.setText(_translate("MainWindow", "最低粉丝"))
        self.HintMaxFans.setText(_translate("MainWindow", "最高粉丝"))
        self.HintPersonCount.setText(_translate("MainWindow", "当前用户池总人数"))
        self.PushLottery.setText(_translate("MainWindow", "开始抽奖"))
        self.PushClear.setText(_translate("MainWindow", "清空日志"))
        self.CheckAutoClear.setText(_translate("MainWindow", "自动清空"))
        self.CheckAutoSave.setText(_translate("MainWindow", "保存抽奖"))
        self.RadioOr.setText(_translate("MainWindow", "或（并集）"))
        self.RadioAnd.setText(_translate("MainWindow", "且（交集）"))
        self.CheckBlackList.setText(_translate("MainWindow", "启用黑名单"))
